### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by geksilla** [atom-community/environment#10]
Thanks for great plugin. Is there are any plans to support linux as well?

**Comment by Arcanemagus** [comment]
Linux support is built in, since it was never needed in the first place. This package is only intended to work around the fact that OS X gives applications launched from the GUI a (almost) completely blank environment, meaning essentially no CLI tools can be found.

**Comment by geksilla** [comment]
I also was running atom from GUI and had same issue... Let me check it again. I think that I've seen issues reported to electron and atom from Linux users.

**Comment by geksilla** [comment]
It's probably my local issue, but my default shell is `/bin/zsh` and `process.env.SHELL` show it as well. But `process.env.PATH` not correct. Seems like it shows PATH from `sh` or `bash`.

**Comment by rasschaert** [comment]
I'm having the same issue on Arch Linux with zsh. My environment is not correctly passed to Atom when I launch it from dmenu. When launching Atom from the shell it works fine.

**Comment by yookoala** [comment]
If you're opening atom with standard Launcher, the environment fails completely. The problem is that Unity / GNOME [doesn't read `.bashrc` or `.profile` to get your `env` parameters at all](http://askubuntu.com/questions/139195/how-to-include-an-environment-variable-in-the-launcher/139198#139198). That's why Atom is not picking up your local `env` on start.

What user can do (for now)
-----------------------------------

What users might do now is:

1. [Set your `env` settings on `/etc/environment`](http://askubuntu.com/questions/94622/how-to-add-a-user-environment-aware-application-launcher-to-unity-panel/105093#105093) (but you'd have the settings global).
2. Manually modify your `atom.desktop` file (should be in `/usr/share/applications`). Modify the line `Exec=/opt/atom/atom %F` to `sh -c "/opt/atom/atom %F"`
3. Similar to (2), but instead of modifying the file directly, you can save the modified file as `$HOME/.local/share/applications/atom.desktop`. Remember to also change `Name=Atom` to `Name=Atom (Local)` before save. Restart your desktop session and you should be able to find "Atom (Local)" in your launcher.
4. Use terminal to open Atom. If you use command line to open Atom, it can pick up `env` in your shell. (say bye bye to your nice application icon)

The truth is, these method sucks.

Suggestion
--------------

I really hope that this module allow user to override `env` setting file in come config file. Something like this:

```
{
  "PATH": "$PATH:$HOME/bin",
  "SOME_ENV": "local.settings.string"
}
```

**Comment by joefitzgerald** [comment]
This package is deprecated; you should uninstall it. See https://github.com/atom/atom/pull/12562 for more information.
